export const colorOptions = [
    { value: 'LightCoral', label: 'LightCoral', hex: '#F08080', group: 'Reds' },
    { value: 'IndianRed', label: 'IndianRed', hex: '#CD5C5C', group: 'Reds' },
    { value: 'Crimson', label: 'Crimson', hex: '#DC143C', group: 'Reds' },
    { value: 'FireBrick', label: 'FireBrick', hex: '#B22222', group: 'Reds' },
    { value: 'Red', label: 'Red', hex: '#FF0000', group: 'Reds' },
    { value: 'DarkRed', label: 'DarkRed', hex: '#8B0000', group: 'Reds' },

    { value: 'LightSalmon', label: 'LightSalmon', hex: '#FFA07A', group: 'Oranges' },
    { value: 'Salmon', label: 'Salmon', hex: '#FA8072', group: 'Oranges' },
    { value: 'DarkSalmon', label: 'DarkSalmon', hex: '#E9967A', group: 'Oranges' },
    { value: 'LightCoral', label: 'LightCoral', hex: '#F08080', group: 'Oranges' },
    { value: 'Coral', label: 'Coral', hex: '#FF7F50', group: 'Oranges' },
    { value: 'Tomato', label: 'Tomato', hex: '#FF6347', group: 'Oranges' },
    { value: 'OrangeRed', label: 'OrangeRed', hex: '#FF4500', group: 'Oranges' },
    { value: 'DarkOrange', label: 'DarkOrange', hex: '#FF8C00', group: 'Oranges' },
    { value: 'Orange', label: 'Orange', hex: '#FFA500', group: 'Oranges' },

    { value: 'Gold', label: 'Gold', hex: '#FFD700', group: 'Yellows' },
    { value: 'Yellow', label: 'Yellow', hex: '#FFFF00', group: 'Yellows' },
    { value: 'LightYellow', label: 'LightYellow', hex: '#FFFFE0', group: 'Yellows' },
    { value: 'LemonChiffon', label: 'LemonChiffon', hex: '#FFFACD', group: 'Yellows' },
    { value: 'LightGoldenRodYellow', label: 'LightGoldenRodYellow', hex: '#FAFAD2', group: 'Yellows' },
    { value: 'PapayaWhip', label: 'PapayaWhip', hex: '#FFEFD5', group: 'Yellows' },
    { value: 'Moccasin', label: 'Moccasin', hex: '#FFE4B5', group: 'Yellows' },
    { value: 'PeachPuff', label: 'PeachPuff', hex: '#FFDAB9', group: 'Yellows' },
    { value: 'PaleGoldenRod', label: 'PaleGoldenRod', hex: '#EEE8AA', group: 'Yellows' },
    { value: 'Khaki', label: 'Khaki', hex: '#F0E68C', group: 'Yellows' },
    { value: 'DarkKhaki', label: 'DarkKhaki', hex: '#BDB76B', group: 'Yellows' },


    { value: 'GreenYellow', label: 'GreenYellow', hex: '#ADFF2F', group: 'Greens' },
    { value: 'Chartreuse', label: 'Chartreuse', hex: '#7FFF00', group: 'Greens' },
    { value: 'LawnGreen', label: 'LawnGreen', hex: '#7CFC00', group: 'Greens' },
    { value: 'Lime', label: 'Lime', hex: '#00FF00', group: 'Greens' },
    { value: 'LimeGreen', label: 'LimeGreen', hex: '#32CD32', group: 'Greens' },
    { value: 'PaleGreen', label: 'PaleGreen', hex: '#98FB98', group: 'Greens' },
    { value: 'LightGreen', label: 'LightGreen', hex: '#90EE90', group: 'Greens' },
    { value: 'MediumSpringGreen', label: 'MediumSpringGreen', hex: '#00FA9A', group: 'Greens' },
    { value: 'SpringGreen', label: 'SpringGreen', hex: '#00FF7F', group: 'Greens' },
    { value: 'MediumSeaGreen', label: 'MediumSeaGreen', hex: '#3CB371', group: 'Greens' },
    { value: 'SeaGreen', label: 'SeaGreen', hex: '#2E8B57', group: 'Greens' },
    { value: 'ForestGreen', label: 'ForestGreen', hex: '#228B22', group: 'Greens' },
    { value: 'Green', label: 'Green', hex: '#008000', group: 'Greens' },
    { value: 'DarkGreen', label: 'DarkGreen', hex: '#006400', group: 'Greens' },

    { value: 'LightSeaGreen', label: 'LightSeaGreen', hex: '#20B2AA', group: 'Cyans' },
    { value: 'Cyan', label: 'Cyan', hex: '#00FFFF', group: 'Cyans' },
    { value: 'Aqua', label: 'Aqua', hex: '#00FFFF', group: 'Cyans' },
    { value: 'Aquamarine', label: 'Aquamarine', hex: '#7FFFD4', group: 'Cyans' },
    { value: 'MediumTurquoise', label: 'MediumTurquoise', hex: '#48D1CC', group: 'Cyans' },
    { value: 'Turquoise', label: 'Turquoise', hex: '#40E0D0', group: 'Cyans' },
    { value: 'DarkTurquoise', label: 'DarkTurquoise', hex: '#00CED1', group: 'Cyans' },
    { value: 'LightCyan', label: 'LightCyan', hex: '#E0FFFF', group: 'Cyans' },
    { value: 'PaleTurquoise', label: 'PaleTurquoise', hex: '#AFEEEE', group: 'Cyans' },
    { value: 'CadetBlue', label: 'CadetBlue', hex: '#5F9EA0', group: 'Cyans' },
    { value: 'DarkCyan', label: 'DarkCyan', hex: '#008B8B', group: 'Cyans' },
    { value: 'Teal', label: 'Teal', hex: '#008080', group: 'Cyans' },

    { value: 'LightSteelBlue', label: 'LightSteelBlue', hex: '#B0C4DE', group: 'Blues' },
    { value: 'PowderBlue', label: 'PowderBlue', hex: '#B0E0E6', group: 'Blues' },
    { value: 'LightBlue', label: 'LightBlue', hex: '#ADD8E6', group: 'Blues' },
    { value: 'SkyBlue', label: 'SkyBlue', hex: '#87CEEB', group: 'Blues' },
    { value: 'LightSkyBlue', label: 'LightSkyBlue', hex: '#87CEFA', group: 'Blues' },
    { value: 'DeepSkyBlue', label: 'DeepSkyBlue', hex: '#00BFFF', group: 'Blues' },
    { value: 'DodgerBlue', label: 'DodgerBlue', hex: '#1E90FF', group: 'Blues' },
    { value: 'CornflowerBlue', label: 'CornflowerBlue', hex: '#6495ED', group: 'Blues' },
    { value: 'SteelBlue', label: 'SteelBlue', hex: '#4682B4', group: 'Blues' },
    { value: 'RoyalBlue', label: 'RoyalBlue', hex: '#4169E1', group: 'Blues' },
    { value: 'Blue', label: 'Blue', hex: '#0000FF', group: 'Blues' },
    { value: 'MediumBlue', label: 'MediumBlue', hex: '#0000CD', group: 'Blues' },
    { value: 'DarkBlue', label: 'DarkBlue', hex: '#00008B', group: 'Blues' },
    { value: 'Navy', label: 'Navy', hex: '#000080', group: 'Blues' },
    { value: 'MidnightBlue', label: 'MidnightBlue', hex: '#191970', group: 'Blues' },

    { value: 'Lavender', label: 'Lavender', hex: '#E6E6FA', group: 'Purples' },
    { value: 'Thistle', label: 'Thistle', hex: '#D8BFD8', group: 'Purples' },
    { value: 'Plum', label: 'Plum', hex: '#DDA0DD', group: 'Purples' },
    { value: 'Violet', label: 'Violet', hex: '#EE82EE', group: 'Purples' },
    { value: 'Orchid', label: 'Orchid', hex: '#DA70D6', group: 'Purples' },
    { value: 'Fuchsia', label: 'Fuchsia', hex: '#FF00FF', group: 'Purples' },
    { value: 'Magenta', label: 'Magenta', hex: '#FF00FF', group: 'Purples' },
    { value: 'MediumOrchid', label: 'MediumOrchid', hex: '#BA55D3', group: 'Purples' },
    { value: 'MediumPurple', label: 'MediumPurple', hex: '#9370DB', group: 'Purples' },
    { value: 'BlueViolet', label: 'BlueViolet', hex: '#8A2BE2', group: 'Purples' },
    { value: 'DarkViolet', label: 'DarkViolet', hex: '#9400D3', group: 'Purples' },
    { value: 'DarkOrchid', label: 'DarkOrchid', hex: '#9932CC', group: 'Purples' },
    { value: 'DarkMagenta', label: 'DarkMagenta', hex: '#8B008B', group: 'Purples' },
    { value: 'Purple', label: 'Purple', hex: '#800080', group: 'Purples' },
    { value: 'Indigo', label: 'Indigo', hex: '#4B0082', group: 'Purples' },
    { value: 'SlateBlue', label: 'SlateBlue', hex: '#6A5ACD', group: 'Purples' },
    { value: 'DarkSlateBlue', label: 'DarkSlateBlue', hex: '#483D8B', group: 'Purples' },



];
